format = """
[â•­â€”](fg:current_line)\
[î‚¶](#28FA97)\
$os\
$shell\
[î‚°](fg:#28FA97 bg:#006FF7)\
$username\
[â–“â–’â–‘](bg:#FEFA38 fg:#006FF7)\
$directory\
[â–“â–’â–‘](fg:#FEFA38 bg:#FCA17D)\
$git_branch\
$git_status\
[â–“â–’â–‘](fg:#FCA17D bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[â–“â–’â–‘](fg:#86BBD8 bg:#06969A)\
$docker_context\
[â–“â–’â–‘](fg:#06969A bg:#33658A)\
$time\
[î‚´](fg:#2E9599)\
$line_break\
\u2570\u2500$character\
"""
# #DA627D
# Disable the blank line at the start of the prompt
add_newline = false

[palettes.foo]
osblue = '#006FF7'
osgreen = '#28FA97'	

[character]
success_symbol = '[ğŸš€ îŠ…](fg:green)'
error_symbol = '[ğŸ’€ îŠ…](fg:red)'
# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#006FF7"
style_root = "bg:#006FF7"
format = '[ ğŸ‘¤$user  ]($style)'
disabled = false

[username.aliases]
"Administrator" = "ó°†¥ Admin "
"user_root" = "ğŸ‘‘ Root "
"user" = "ğŸ‘¤"
# An alternative to the username module which displays a symbol that
# represents the current operating system
[os.symbols]
Alpine = ' ïŒ€ '
Amazon = ' ï‰° '
Android = ' îœ '  
Arch = ' ïŒƒ '
CentOS = ' ïŒ„ '
Debian = ' ïŒ† '
EndeavourOS = ' ïŒ¢ '
Fedora = ' ïŒŠ '
FreeBSD = ' ïŒŒ '
Garuda = ' ï…¼ '
Gentoo = ' ïŒ '
Linux = ' ï…¼ '
Macos = ' ïŒ‚ '
Manjaro = ' ïŒ’ '
Mariner = ' ï…¼ '
Mint = ' ïŒ '
NetBSD = ' ï…¼ '
NixOS = ' ïŒ“ '
OpenBSD = ' ïŒ¨ '
OpenCloudOS = ' î®ª '
openEuler = ' ï…¼ '
openSUSE = ' ïŒ” '
OracleLinux = ' âŠ‚âŠƒ '
Pop = ' ïŒª '
Raspbian = ' ïŒ• '
Redhat = ' ïŒ– '
RedHatEnterprise = ' ïŒ– '
Solus = ' ïŒ­ '
SUSE = ' ïŒ” '
Ubuntu = ' ïŒ› '
Unknown = ' ï„ˆ '
Windows = ' îœ '

[os]
style = "#006FF7 bg:#28FA97"
disabled = false # Disabled by default

[shell]
format = "[$indicator]($style)"  # Customize the output format
bash_indicator = "| ğŸ§ó±†ƒ "
zsh_indicator = "| âš¡"
fish_indicator = "| ğŸ ó°»³ó°»´ó°ˆº"
powershell_indicator = "| îšƒ "
cmd_indicator = "| î¯„CMD "
unknown_indicator = "| â“ "
style = "#006FF7 bg:#28FA97"
disabled = false

[directory]
style = "#003479 bg:#FEFA38"
home_symbol = "ğŸ "
read_only = 'ğŸ”’ '
read_only_style = ''
format = "[ $path ]($style)"
truncation_length = 0
# truncation_symbol = "â€¦/"
truncation_symbol = 'Â»Â« '

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ó°ˆ™ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ó°ˆ™ " = " ó°ˆ™ï„ª "

[c]
symbol = "î˜ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ğŸ³ "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = "î‰µ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï˜"
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "#9A348E bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ó°†¥ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#2E9599"
format = '[ ğŸ•™ $time ]($style)'
#âŒšğŸ•°ï¸â³â°âŒ›

